Removed PYTHONPATH from tox to prevent rest_framework import errors
Otherwise we still get
    from rest_framework import exceptions
    ImportError: cannot import name exceptions

while running the tests in tox because of the import namespace